### ISSUE TITLE
Example use of "query" function

### ISSUE THREAD

**Issue by georgekaf** [firstandthird/tokens#30]
Can't find out how the query function should be used. 

I searched for an example use but I can't find any. Did I miss it somewhere?

**Comment by georgekaf** [comment]
Can't seem to make it work properly

http://jsfiddle.net/george_black/xamxryn6/

**Comment by dawnerd** [comment]
It's not working because callback() is called out of scope in the query method. Something we should probably fix in the lib itself. But at the moment you can use this: http://jsfiddle.net/xamxryn6/16/

**Comment by paulgeorge92** [comment]
I used the query and worked. Below is my code:
$('#query').tokens({
		query: function (query, callback) {
                           this.callback = callback;
                           //Write here your code to fetch the data
                           this.callback(autoCompleteData); //autoCompleteData contains the data
                }
});
